CREATE TYPE TIPO_STATUS_COLECAO AS ENUM ('TENHO', 'LIDO', 'QUERO', 'VENDIDO');
CREATE TYPE TIPO_FUNCAO_AUTOR AS ENUM ('ROTEIRISTA', 'DESENHISTA',
'ARTE-FINALISTA', 'COLORISTA', 'CAPISTA');

CREATE TABLE USUARIO (
id_usuario SERIAL NOT NULL,
nome VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL,
senha_hash VARCHAR(255) NOT NULL,
criado_em TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
CONSTRAINT "PK_USUARIO" PRIMARY KEY (id_usuario),
CONSTRAINT "UQ_USUARIO_EMAIL" UNIQUE (email)
);

CREATE TABLE EDITORA (
id_editora SERIAL NOT NULL,
nome VARCHAR(100) NOT NULL,
pais VARCHAR(50),
criado_em TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
CONSTRAINT "PK_EDITORA" PRIMARY KEY (id_editora),
CONSTRAINT "UQ_EDITORA_NOME" UNIQUE (nome)
);

CREATE TABLE AUTOR (
id_autor SERIAL NOT NULL,
nome VARCHAR(150) NOT NULL,
pseudonimo VARCHAR(100),
criado_em TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
CONSTRAINT "PK_AUTOR" PRIMARY KEY (id_autor)
);

CREATE TABLE GENERO (
id_genero SERIAL NOT NULL,
nome VARCHAR(50) NOT NULL,
CONSTRAINT "PK_GENERO" PRIMARY KEY (id_genero),
CONSTRAINT "UQ_GENERO_NOME" UNIQUE (nome)
);

CREATE TABLE QUADRINHO (
id_quadrinho SERIAL NOT NULL,
titulo VARCHAR(255) NOT NULL,
sinopse TEXT,
numero_edicao INTEGER,
ano_edicao INTEGER,
paginas INTEGER,
isbn VARCHAR(20),
capa_url VARCHAR(255),
criado_em TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
id_editora INTEGER NOT NULL,
CONSTRAINT "PK_QUADRINHO" PRIMARY KEY (id_quadrinho),
CONSTRAINT "UQ_QUADRINHO_ISBN" UNIQUE (isbn),
CONSTRAINT "FK_QUADRINHO_EDITORA" FOREIGN KEY (id_editora) REFERENCES
EDITORA(id_editora)
);

CREATE TABLE QUADRINHO_AUTOR (
id_quadrinho INTEGER NOT NULL,
id_autor INTEGER NOT NULL,
funcao TIPO_FUNCAO_AUTOR NOT NULL,
CONSTRAINT "PK_QUADRINHO_AUTOR" PRIMARY KEY (id_quadrinho, id_autor, funcao),
CONSTRAINT "FK_QA_QUADRINHO" FOREIGN KEY (id_quadrinho) REFERENCES
QUADRINHO(id_quadrinho) ON DELETE CASCADE,
CONSTRAINT "FK_QA_AUTOR" FOREIGN KEY (id_autor) REFERENCES AUTOR(id_autor)
ON DELETE CASCADE
);

CREATE TABLE QUADRINHO_GENERO (
id_quadrinho INTEGER NOT NULL,
id_genero INTEGER NOT NULL,
CONSTRAINT "PK_QUADRINHO_GENERO" PRIMARY KEY (id_quadrinho, id_genero),
CONSTRAINT "FK_QG_QUADRINHO" FOREIGN KEY (id_quadrinho) REFERENCES
QUADRINHO(id_quadrinho) ON DELETE CASCADE,
CONSTRAINT "FK_QG_GENERO" FOREIGN KEY (id_genero) REFERENCES
GENERO(id_genero) ON DELETE CASCADE
);

CREATE TABLE COLECAO (
id_colecao SERIAL NOT NULL,
id_usuario INTEGER NOT NULL,
id_quadrinho INTEGER NOT NULL,
status TIPO_STATUS_COLECAO NOT NULL,
data_lido DATE,
data_adicionado TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
CONSTRAINT "PK_COLECAO" PRIMARY KEY (id_colecao),
CONSTRAINT "FK_COLECAO_USUARIO" FOREIGN KEY (id_usuario) REFERENCES
USUARIO(id_usuario) ON DELETE CASCADE,
CONSTRAINT "FK_COLECAO_QUADRINHO" FOREIGN KEY (id_quadrinho) REFERENCES
QUADRINHO(id_quadrinho) ON DELETE CASCADE,
CONSTRAINT "UQ_COLECAO_USUARIO_QUADRINHO" UNIQUE (id_usuario, id_quadrinho)
);

CREATE TABLE AVALIACAO (
id_avaliacao SERIAL NOT NULL,
id_usuario INTEGER NOT NULL,
id_quadrinho INTEGER NOT NULL,
roteiro SMALLINT NOT NULL,
arte SMALLINT NOT NULL,
cores SMALLINT NOT NULL,
edicao SMALLINT NOT NULL,
comentario TEXT,
criado_em TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
CONSTRAINT "PK_AVALIACAO" PRIMARY KEY (id_avaliacao),
CONSTRAINT "FK_AVALIACAO_USUARIO" FOREIGN KEY (id_usuario) REFERENCES
USUARIO(id_usuario) ON DELETE CASCADE,
CONSTRAINT "FK_AVALIACAO_QUADRINHO" FOREIGN KEY (id_quadrinho)
REFERENCES QUADRINHO(id_quadrinho) ON DELETE CASCADE,
CONSTRAINT "UQ_AVALIACAO_USUARIO_QUADRINHO" UNIQUE (id_usuario,
id_quadrinho),
CONSTRAINT "CHK_NOTA_ROTEIRO" CHECK (roteiro BETWEEN 1 AND 10),
CONSTRAINT "CHK_NOTA_ARTE" CHECK (arte BETWEEN 1 AND 10),
CONSTRAINT "CHK_NOTA_CORES" CHECK (cores BETWEEN 1 AND 10),
CONSTRAINT "CHK_NOTA_EDICAO" CHECK (edicao BETWEEN 1 AND 10)
);
